### ISSUE TITLE
Advanced solar helmet times out players on server

### ISSUE THREAD

**Issue by cd-JL** [Trinsdar/Advanced-Solars-Classic-Edition#2]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_184429_b(Lnet/minecraft/item/ItemStack;)I
        at trinsdar.advancedsolars.items.ItemArmorAdvancedSolarHelmet.chargeInventory(ItemArmorAdvancedSolarHelmet.java:113) ~[ItemArmorAdvancedSolarHelmet.class:?]
        at trinsdar.advancedsolars.items.ItemArmorAdvancedSolarHelmet.onArmorTick(ItemArmorAdvancedSolarHelmet.java:68) ~[ItemArmorAdvancedSolarHelmet.class:?]
        at net.minecraft.entity.player.InventoryPlayer.decrementAnimations(InventoryPlayer.java:371) ~[aec.class:?]
        at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:511) ~[aed.class:?]
        at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382) ~[oq.class:?]

**Comment by cd-JL** [comment]
it happened as soon as he walked outside with it on
